### ISSUE TITLE
[BUG] Editor crahsing when pasting some links

### ISSUE THREAD

**Issue by Rafa7046** [Darginec05/Yoopta-Editor#319] opened 2024-09-27 20:44 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Whenever I paste certain links into the editor, the entire site crashes instantly, and I have to refresh or restart it to continue using the platform. In my case it crashes with the image url generated by DALL-e i didnt manage to find other links yet but it probably has.

### Steps to Reproduce

Go to any Yoopta-editor, for example using the [Yoopta](https://yoopta.dev/examples/withBaseFullSetup) and paste a image url generated by DALL-e, (the image expires after 30 min but the error still persists)

https://oaidalleapiprodscus.blob.core.windows.net/private/org-iPs6dlUwT1DdySPPMvn86Mai/user-Bz8M1Lxnr5nSJ3vs8Qz9q39H/img-VcK1te1Vk0h5YwK2cy30XzNF.png?st=2024-09-27T15%3A40%3A22Z&se=2024-09-27T17%3A40%3A22Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-09-26T23%3A51%3A59Z&ske=2024-09-27T23%3A51%3A59Z&sks=b&skv=2024-08-04&sig=rfwaMoRxe85iPJ0X9hzRO4SRyXnUIChBa0/T3vVs640%3D

### Environment

- Browser:

### Screenshots

https://github.com/user-attachments/assets/b1978cd2-ca16-4597-a65e-0fcdce3c424c

### Do you want to work on this issue?

No

**Comment by Zaid-B24** [comment] 2024-10-09 10:17
I think the problem is in DALL-e authentication

**Comment by Rafa7046** [comment] 2024-10-24 16:02
I dont think it is, i just crashed the editor with another ctrl + v, i just pasted random letters, example:
wqbjflhasdbfkjasdhbfkljsbnafnkbnsqjkbvhjlaxbkjlhvbsqahjkhbfvnmasbvmndbasnfmvbkjdqbnvkmjsbnkjvbakjsnvkasbvkjabskjvb

And the whole editor crashed

**Comment by Darginec05** [comment] 2024-10-24 16:29
Found the [problem] (https://github.com/Darginec05/Yoopta-Editor/blob/master/packages/core/editor/src/plugins/extenstions/withInlines.ts#L77)

Fix will be included in the next patch version

**Comment by Darginec05** [comment] 2024-10-31 14:03
Fixed in v4.9.1

**Closed by Darginec05** 2024-10-31 14:03 UTC
