### ISSUE TITLE
[BUG]  TypeError: c is not a function

### ISSUE THREAD

**Issue by lucifermorningstar1305** [Darginec05/Yoopta-Editor#230] opened 2024-07-27 01:39 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

TypeError: c is not a function
    at ee (index.js:12:11828)
    at renderWithHooks (react-dom.development.js:11121:18)
    at mountIndeterminateComponent (react-dom.development.js:16869:13)
    at beginWork$1 (react-dom.development.js:18458:16)
    at beginWork (react-dom.development.js:26927:14)
    at performUnitOfWork (react-dom.development.js:25748:12)
    at workLoopSync (react-dom.development.js:25464:5)
    at renderRootSync (react-dom.development.js:25419:7)
    at recoverFromConcurrentError (react-dom.development.js:24597:20)
    at performSyncWorkOnRoot (react-dom.development.js:24899:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:7758:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:7718:3)
    at processRootScheduleInMicrotask (react-dom.development.js:7863:3)
    at eval (react-dom.development.js:8034:7)

### Steps to Reproduce

1. Type something on the Editor.
1. After typing a few words, simply try selecting those words using your mouse

### Environment

- OS: Pop_OS! 22.04
- Browser: Brave

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment] 2024-07-27 18:45
Hi @lucifermorningstar1305 👋
What the bundle react you are using? 
CRA, Vite, NextJS?

**Comment by lucifermorningstar1305** [comment] 2024-07-27 18:47
Hey @Darginec05 I am using NextJS 14.

**Comment by Darginec05** [comment] 2024-07-28 14:39
@lucifermorningstar1305 still can't reproduce issue in browser Brave with next@14.
Could you please open "index.js:12:11828" in console tab and send me a screenshot of the code?

**Comment by lucifermorningstar1305** [comment] 2024-07-28 16:31
Hi @Darginec05 , sure here's a screenshot:

![image](https://github.com/user-attachments/assets/ae9c4efd-c9fd-4fe2-8d12-71f1e9d41f07)

**Comment by Darginec05** [comment] 2024-07-28 19:20
@lucifermorningstar1305 thanks for quick response.
Is it work if you comment `ActionMenu` in `tools` object?

**Comment by lucifermorningstar1305** [comment] 2024-07-28 19:32
Hey @Darginec05, yeah it does work if I comment out `ActionMenu` in tools object. But the thing is I do need the `ActionMenu` as I want to integrate the Notion-like feature in my app.

**Comment by lucifermorningstar1305** [comment] 2024-07-28 19:39
Also, I am trying to get all the text that I am going to type on the notes. Can you please point me to the right function?

**Comment by Darginec05** [comment] 2024-07-28 20:38
@lucifermorningstar1305 yeah, sure!
I just wanted to clarify where this bug appears.

So, I'll check `ActionMenu` and ping you then

**Comment by lucifermorningstar1305** [comment] 2024-07-28 21:10
Hey @Darginec05 I just found out the bug and solved it! Well, I copied this code block from the `README.md` , and apparently the error is in the value of `TOOLS.ActionMenu.tool`. It should be `ActionMenu`. So I replaced that and it's working like a charm. 😄

```{javascript}
// IMPORT TOOLS
import LinkTool, { DefaultLinkToolRender } from '@yoopta/link-tool';
import ActionMenu, { DefaultActionMenuRender } from '@yoopta/action-menu-list';
import Toolbar, { DefaultToolbarRender } from '@yoopta/toolbar';

// Tools should be defined outside component
const TOOLS = {
  Toolbar: {
    tool: Toolbar,
    render: DefaultToolbarRender,
  },
  ActionMenu: {
    tool: Toolbar,
    render: DefaultActionMenuRender,
  },
  LinkTool: {
    tool: LinkTool,
    render: DefaultLinkToolRender,
  },
};

export default function Editor() {
  const editor = useMemo(() => createYooptaEditor(), []);

  return (
    <div>
      <YooptaEditor
        editor={editor}
        plugins={plugins}
        placeholder="Type text.."
        // here we go
        tools={TOOLS}
      />
    </div>
  );
}
```

**Comment by NTablang** [comment] 2024-07-29 00:07
Thank you for the comment today haha! Was trying out the editor for funsies just now and was facing this issue! Made a PR to updated the README! https://github.com/Darginec05/Yoopta-Editor/pull/233

**Comment by Darginec05** [comment] 2024-07-29 08:50
@lucifermorningstar1305 oh, my bad, pardon :D
@NTablang thanks for PR and fixing docs! 

Merged  ✅

**Closed by Darginec05** 2024-07-29 08:50 UTC
